name: minecraft-arzamas
services:

  database:
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          cpus: "1"
          memory: "512M"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    image: mysql:8
    networks:
      - default
      - monitoring
    ports:
      - "127.0.0.1:3306:3306/tcp"
    restart: always
    stop_grace_period: 10m0s
    volumes:
      - ./mysql-config:/etc/mysql/conf.d:ro
      - database:/var/lib/mysql:rw

  server:
    depends_on:
      database:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: "4G"
        reservations:
          cpus: "2"
          memory: "4G"
    environment:
      JAVA_PARAMS: >
        -XX:+UseContainerSupport
        -XX:MinRAMPercentage=10.0 -XX:MaxRAMPercentage=90 -XX:InitialRAMPercentage=90.0
        -XX:+AlwaysPreTouch
        -XX:+UnlockExperimentalVMOptions
        -XX:+UseZGC -XX:-ZUncommit
        -XX:+DisableExplicitGC
        -XX:+UseDynamicNumberOfGCThreads
        -Dsun.rmi.dgc.client.gcInterval=2147483646 -Dsun.rmi.dgc.server.gcInterval=2147483646
        -Dcom.sun.management.jmxremote.port=1234 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false 
    image: hyperpaint/minecraft-arzamas:1.20.1
    networks:
      - default
      - monitoring
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "127.0.0.1:1234:1234/tcp"
      - "127.0.0.1:1234:1234/udp"
    restart: always
    stop_grace_period: 10m0s
    volumes:
      - server:/root/server:rw

  scheduler:
    depends_on:
      server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: "32M"
        reservations:
          cpus: "0.1"
          memory: "32M"
    environment:
      MCRCON_HOST: server
      # Параметры скриптов
      # backup.sh
      BACKUP_DIRECTORY_SOURCE: /root/server
      BACKUP_DIRECTORY_TARGET: /root/backup
      BACKUP_HISTORY_COUNT: 4
      BACKUP_TAR_PARAMS: ""
      # clear-drop.sh
      CLEAR_DROP_CHECK_TRIGGER: 300
      CLEAR_DROP_TIME_TO_WAIT: 30
      CLEAR_DROP_TIME_TO_WAIT_STEP: 5
      # reboot.sh
      REBOOT_TIME_TO_WAIT: 60
      REBOOT_TIME_TO_WAIT_STEP: 5
    image: hyperpaint/minecraft-scheduler:1.0.0-1
    networks:
      - default
    restart: always
    volumes:
      - server:/root/server:ro
      - scheduler-logs:/root/logs:rw
      - ./custom-scripts:/root/custom-scripts:rw
      - ./backup:/root/backup:rw

  proxy-http:
    depends_on:
      server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: "32M"
        reservations:
          cpus: "0.1"
          memory: "32M"
    image: nginx:1.25.2
    networks:
      - default
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d:ro
      - ./nginx-certs/nginx-self-signed.key:/etc/nginx/certificate.key:ro
      - ./nginx-certs/nginx-self-signed.pem:/etc/nginx/certificate.pem:ro
      - ./nginx-data:/usr/share/nginx/html:ro

networks:
  default:
    name: minecraft-arzamas-default
  monitoring:
    name: monitoring-default
    external: true

volumes:
  database:
    name: minecraft-database
  server:
    name: minecraft-arzamas-server
  scheduler-logs:
    name: minecraft-arzamas-scheduler-logs
