name: frog-is-mine
services:

  wordpress:
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "384M"
        reservations:
          cpus: "0.1"
          memory: "384M"
    image: hyperpaint/wordpress:6.4.3
    networks:
      - default
      - shared
    restart: always
    volumes:
      - ./wordpress-config/wp-config.php:/var/www/html/wp-config.php:ro
      - ./wordpress-config/htaccess:/var/www/html/.htaccess:ro
      - ./wordpress-config/advanced-cache.php:/var/www/html/wp-content/advanced-cache.php:ro
      - ./wordpress-config/wp-cache-config.php:/var/www/html/wp-content/wp-cache-config.php:ro
      - wordpress-mu-plugins:/var/www/html/wp-content/mu-plugins:rw
      - wordpress-plugins:/var/www/html/wp-content/plugins:rw
      - wordpress-themes:/var/www/html/wp-content/themes:rw
      - wordpress-languages:/var/www/html/wp-content/languages:rw
      - wordpress-data:/var/www/html/wp-content/uploads:rw

  proxy-http:
    depends_on:
      wordpress:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "32M"
        reservations:
          cpus: "0.1"
          memory: "32M"
    image: nginx:1.25.2
    networks:
      - default
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "8443:8443/tcp"
    restart: always
    volumes:
      - ./nginx-config:/etc/nginx/conf.d:ro
      - ./nginx-certs/nginx-self-signed.key:/etc/nginx/certificate.key:ro
      - ./nginx-certs/nginx-self-signed.pem:/etc/nginx/certificate.pem:ro
      - ./nginx-data:/usr/share/nginx/html:ro

networks:
  default:
  shared:
    name: shared_default
    external: true

volumes:
  wordpress-mu-plugins:
  wordpress-plugins:
  wordpress-themes:
  wordpress-languages:
  wordpress-data:
