global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - localhost:9090
- job_name: node-exporter
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      # Node exporter
      - 172.20.0.1:9100
      labels:
        server: 'if-the-sea-were-vodka'
- job_name: app
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - minecraft-arzamas-server:9225
      labels:
        game: 'minecraft'
        mod: 'arzamas'
